site_name: celligner
theme: readthedocs
plugins:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.modules["mnnpy"] = mock()
            - sys.modules["limmapy"] = mock()